/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_sketch_toolkit_JMatLink */

#ifndef _Included_edu_mit_sketch_toolkit_JMatLink
#define _Included_edu_mit_sketch_toolkit_JMatLink
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: threadInitNumber */
/* Inaccessible static: stopThreadPermission */
#undef edu_mit_sketch_toolkit_JMatLink_MIN_PRIORITY
#define edu_mit_sketch_toolkit_JMatLink_MIN_PRIORITY 1L
#undef edu_mit_sketch_toolkit_JMatLink_NORM_PRIORITY
#define edu_mit_sketch_toolkit_JMatLink_NORM_PRIORITY 5L
#undef edu_mit_sketch_toolkit_JMatLink_MAX_PRIORITY
#define edu_mit_sketch_toolkit_JMatLink_MAX_PRIORITY 10L
#undef edu_mit_sketch_toolkit_JMatLink_idleI
#define edu_mit_sketch_toolkit_JMatLink_idleI 0L
#undef edu_mit_sketch_toolkit_JMatLink_engOpenI
#define edu_mit_sketch_toolkit_JMatLink_engOpenI 1L
#undef edu_mit_sketch_toolkit_JMatLink_engCloseI
#define edu_mit_sketch_toolkit_JMatLink_engCloseI 2L
#undef edu_mit_sketch_toolkit_JMatLink_engEvalStringI
#define edu_mit_sketch_toolkit_JMatLink_engEvalStringI 3L
#undef edu_mit_sketch_toolkit_JMatLink_engGetScalarI
#define edu_mit_sketch_toolkit_JMatLink_engGetScalarI 4L
#undef edu_mit_sketch_toolkit_JMatLink_engGetVectorI
#define edu_mit_sketch_toolkit_JMatLink_engGetVectorI 5L
#undef edu_mit_sketch_toolkit_JMatLink_engGetArrayI
#define edu_mit_sketch_toolkit_JMatLink_engGetArrayI 6L
#undef edu_mit_sketch_toolkit_JMatLink_engPutArray2dI
#define edu_mit_sketch_toolkit_JMatLink_engPutArray2dI 9L
#undef edu_mit_sketch_toolkit_JMatLink_engOutputBufferI
#define edu_mit_sketch_toolkit_JMatLink_engOutputBufferI 10L
#undef edu_mit_sketch_toolkit_JMatLink_engGetCharArrayI
#define edu_mit_sketch_toolkit_JMatLink_engGetCharArrayI 11L
#undef edu_mit_sketch_toolkit_JMatLink_destroyJMatLinkI
#define edu_mit_sketch_toolkit_JMatLink_destroyJMatLinkI 12L
#undef edu_mit_sketch_toolkit_JMatLink_engOpenSingleUseI
#define edu_mit_sketch_toolkit_JMatLink_engOpenSingleUseI 13L
/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_mit_sketch_toolkit_JMatLink_displayHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engTestNATIVE
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engTestNATIVE
  (JNIEnv *, jobject);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engOpenNATIVE
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engOpenNATIVE
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engOpenSingleUseNATIVE
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engOpenSingleUseNATIVE
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engCloseNATIVE
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engCloseNATIVE
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engEvalStringNATIVE
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engEvalStringNATIVE
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engGetScalarNATIVE
 * Signature: (ILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engGetScalarNATIVE
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engGetVectorNATIVE
 * Signature: (ILjava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engGetVectorNATIVE
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engGetArrayNATIVE
 * Signature: (ILjava/lang/String;)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engGetArrayNATIVE
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engGetCharArrayNATIVE
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engGetCharArrayNATIVE
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engPutArrayNATIVE
 * Signature: (ILjava/lang/String;[[D)V
 */
JNIEXPORT void JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engPutArrayNATIVE
  (JNIEnv *, jobject, jint, jstring, jobjectArray);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    engOutputBufferNATIVE
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_mit_sketch_toolkit_JMatLink_engOutputBufferNATIVE
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_mit_sketch_toolkit_JMatLink
 * Method:    setDebugNATIVE
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_edu_mit_sketch_toolkit_JMatLink_setDebugNATIVE
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
