/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_sketch_toolkit_Timer */

#ifndef _Included_edu_mit_sketch_toolkit_Timer
#define _Included_edu_mit_sketch_toolkit_Timer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_sketch_toolkit_Timer
 * Method:    getTics
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_mit_sketch_toolkit_Timer_getTics
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
